language: php

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  -
  - mkdir -p ~/.aws
  - touch ~/.aws/credentials
  - echo "[default"] >> ~/.aws/credentials
  - echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials
  - echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials

before_script:
  - npm install -g less

branches:
  only:
    - master
  
script:
  - lessc -x less/daux-navy.less >css/daux-navy.min.css
  - php index.php generate
  - # front page is Getting_Started.html
  - cp static/Getting_Started/Getting_Started.html static/index.html
  - # copy additional files
  - cp add-ons/* static/
  - aws s3 sync --delete --exclude "reference/*" --acl public-read static s3://docs.testfairy.com/
  - aws cloudfront create-invalidation --distribution-id $CF_DISTRIBUTION_ID --paths '/*'


