language: php

before_install:
  - openssl aes-256-cbc -K $encrypted_968efea6ce8c_key -iv $encrypted_968efea6ce8c_iv -in id_docs.key.enc -out id_docs.key -d

before_script:
  - npm install less

branches:
  only:
    - master
  
script:
  - lessc -x less/daux-navy.less >css/daux-navy.min.css
  - php index.php generate
  - cp static/API/Upload_API.html static/index.html
  - cp 404/* static/
  - cp 404/.htaccess static/
  - curl -s http://checkip.amazonaws.com/
  - chmod 0600 id_docs.key
  - chmod 0600 static/.htaccess
  - scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i id_docs.key -r static/* $REMOTE_DOCS_LOCATION
  - scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i id_docs.key static/.htaccess $REMOTE_DOCS_LOCATION

